//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace mdview.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("mdview.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Are you sure to clear recent items? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AREYOUSURETO_CLEAR_RECENTS {
            get {
                return ResourceManager.GetString("AREYOUSURETO_CLEAR_RECENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Clear all に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CLEAR_ALL_RECENTS {
            get {
                return ResourceManager.GetString("CLEAR_ALL_RECENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clear &amp;non-existent に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CLEAR_NONEXISTENT_RECENTS {
            get {
                return ResourceManager.GetString("CLEAR_NONEXISTENT_RECENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   English に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CLI_ENGLISH {
            get {
                return ResourceManager.GetString("CLI_ENGLISH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Japanese に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CLI_JAPANESE {
            get {
                return ResourceManager.GetString("CLI_JAPANESE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System default に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CLI_SYSTEMDEFAULT {
            get {
                return ResourceManager.GetString("CLI_SYSTEMDEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to save ini. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string INI_SAVE_FAILED {
            get {
                return ResourceManager.GetString("INI_SAVE_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No markdown executables registered, organize them first or remove mdview.ini to register default markdowns. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NO_MARKDOWN {
            get {
                return ResourceManager.GetString("NO_MARKDOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;No recent items&gt; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NO_RECENT_ITEM {
            get {
                return ResourceManager.GetString("NO_RECENT_ITEM", resourceCulture);
            }
        }
    }
}
