//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mdview.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("mdview.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to clear recent items?.
        /// </summary>
        internal static string AREYOUSURETO_CLEAR_RECENTS {
            get {
                return ResourceManager.GetString("AREYOUSURETO_CLEAR_RECENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Clear all.
        /// </summary>
        internal static string CLEAR_ALL_RECENTS {
            get {
                return ResourceManager.GetString("CLEAR_ALL_RECENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear &amp;non-existent.
        /// </summary>
        internal static string CLEAR_NONEXISTENT_RECENTS {
            get {
                return ResourceManager.GetString("CLEAR_NONEXISTENT_RECENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string CLI_ENGLISH {
            get {
                return ResourceManager.GetString("CLI_ENGLISH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japanese.
        /// </summary>
        internal static string CLI_JAPANESE {
            get {
                return ResourceManager.GetString("CLI_JAPANESE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System default.
        /// </summary>
        internal static string CLI_SYSTEMDEFAULT {
            get {
                return ResourceManager.GetString("CLI_SYSTEMDEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save ini..
        /// </summary>
        internal static string INI_SAVE_FAILED {
            get {
                return ResourceManager.GetString("INI_SAVE_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor not set. Open Option dialog to set an editor..
        /// </summary>
        internal static string NO_EDITOR {
            get {
                return ResourceManager.GetString("NO_EDITOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No markdown executables registered, organize them first or remove mdview.ini to register default markdowns..
        /// </summary>
        internal static string NO_MARKDOWN {
            get {
                return ResourceManager.GetString("NO_MARKDOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;No recent items&gt;.
        /// </summary>
        internal static string NO_RECENT_ITEM {
            get {
                return ResourceManager.GetString("NO_RECENT_ITEM", resourceCulture);
            }
        }
    }
}
